### ISSUE TITLE
delete todos also when a list is deleted

### ISSUE THREAD

**Issue by bhatvikrant** [renchris/replicache-demo-with-nextjs#1]

**Comment by renchris** [comment]
Hey. Thanks for bringing this up. Made the fix change with the latest commit [fix: delete todos when list is deleted](https://github.com/renchris/replicache-demo-with-nextjs/commit/20804d691169489e3d5bce9a5ff8633299d1167c)

**Comment by bhatvikrant** [comment]
Hey @renchris , I believe you missed changes in `appActions.ts` for deleting todos in the DB as well.

**Comment by bhatvikrant** [comment]
Shall I start a new issue for this?

**Comment by renchris** [comment]
When our local IndexedDB database mutators run with our Replicache instance ex. `rep.mutate.deleteTodo(id)` the equivalent remote SQLite mutators will run with Drizzle from our `mutate` function in `pushActions.ts`.

After pulling for the changes, let me know if you don't see your todo items being deleted upon list deletion in the remote database with the Drizzle Studio tables `https://local.drizzle.studio` and I can look into it further
